# Project 01 - Data Processing

## Step 5 - Calulate Additional Data

In [1]:
import datetime
import numpy as np
import pandas as pd
pd.__version__

'1.2.5'

In [2]:
BASE_PATH = "./data/jh_covid19/csse_covid_19_data/csse_covid_19_daily_reports/"
BASE_PATH_WB = "./data/world_bank/"
BASE_PATH_OUT = "./data/output/"

In [3]:
df_src = pd.read_csv(BASE_PATH_OUT + 'covid_data.csv')
df_src['date']= pd.to_datetime(df_src['date'])
df_src

       Country_Region  Confirmed  Deaths       date Short Code
0         Afghanistan        5.0     0.0 2020-02-24        AFG
1         Afghanistan        5.0     0.0 2020-02-25        AFG
2         Afghanistan        5.0     0.0 2020-02-26        AFG
3         Afghanistan        5.0     0.0 2020-02-27        AFG
4         Afghanistan        5.0     0.0 2020-02-28        AFG
...               ...        ...     ...        ...        ...
151971       Zimbabwe   251646.0  5498.0 2022-05-26        ZWE
151972       Zimbabwe   251959.0  5500.0 2022-05-27        ZWE
151973       Zimbabwe   251959.0  5500.0 2022-05-28        ZWE
151974       Zimbabwe   252092.0  5500.0 2022-05-29        ZWE
151975       Zimbabwe   252092.0  5500.0 2022-05-30        ZWE

[151976 rows x 5 columns]

### 5.1 Calculate Deltas

In [4]:
list_codes = df_src['Short Code'].unique()
list_codes

array(['AFG', 'AGO', 'ALB', 'AND', 'ARE', 'ARG', 'ARM', 'ATG', 'AUS',
       'AUT', 'AZE', 'BDI', 'BEL', 'BEN', 'BFA', 'BGD', 'BGR', 'BHR',
       'BHS', 'BIH', 'BLR', 'BLZ', 'BOL', 'BRA', 'BRB', 'BRN', 'BTN',
       'BWA', 'CAF', 'CAN', 'CHE', 'CHL', 'CHN', 'CIV', 'CMR', 'COD',
       'COG', 'COL', 'COM', 'CPV', 'CRI', 'CUB', 'CYP', 'CZE', 'DEU',
       'DJI', 'DMA', 'DNK', 'DOM', 'DZA', 'ECU', 'EGY', 'ERI', 'ESP',
       'EST', 'ETH', 'FIN', 'FJI', 'FRA', 'FSM', 'GAB', 'GBR', 'GEO',
       'GHA', 'GIN', 'GMB', 'GNB', 'GNQ', 'GRC', 'GRD', 'GTM', 'GUY',
       'HND', 'HRV', 'HTI', 'HUN', 'IDN', 'IND', 'IRL', 'IRN', 'IRQ',
       'ISL', 'ISR', 'ITA', 'JAM', 'JOR', 'JPN', 'KAZ', 'KEN', 'KGZ',
       'KHM', 'KIR', 'KOR', 'KWT', 'LAO', 'LBN', 'LBR', 'LBY', 'LIE',
       'LKA', 'LSO', 'LTU', 'LUX', 'LVA', 'MAR', 'MCO', 'MDA', 'MDG',
       'MDV', 'MEX', 'MHL', 'MKD', 'MLI', 'MLT', 'MMR', 'MNE', 'MNG',
       'MOZ', 'MRT', 'MUS', 'MWI', 'MYS', 'NAM', 'NER', 'NGA', 'NIC',
       'NLD', 'NOR', 'NPL', 'NZL', 'OMN', 'PAK', 'PAN', 'PER', 'PHL',
       'PLW', 'PNG', 'POL', 'PRT', 'PRY', 'PSE', 'QAT', 'ROU', 'RUS',
       'RWA', 'SAU', 'SDN', 'SEN', 'SGP', 'SLB', 'SLE', 'SLV', 'SMR',
       'SOM', 'SRB', 'SSD', 'SUR', 'SVK', 'SVN', 'SWE', 'SWZ', 'SYC',
       'SYR', 'TCD', 'TGO', 'THA', 'TJK', 'TLS', 'TON', 'TTO', 'TUN',
       'TUR', 'TZA', 'UGA', 'UKR', 'URY', 'USA', 'UZB', 'VEN', 'VNM',
       'VUT', 'WSM', 'XKX', 'YEM', 'ZAF', 'ZMB', 'ZWE'], dtype=object)

In [5]:
dfs_by_regions = {}

def get_fatal_rate(confirmed, death):
    if confirmed == 0:
        return 0.
    else:
        return float(death) / float(confirmed)

    
def get_zero_or_result(a, b):
    return 0 if a < b else a - b
    
    
for i in range(len(list_codes)):
    print('processing: ' + list_codes[i])
    df_current_by_region = df_src[df_src['Short Code'] == list_codes[i]]
    df_current_by_region = df_current_by_region.sort_values(by=['date'])
    
    list_confirmed = df_current_by_region['Confirmed'].tolist()
    list_death = df_current_by_region['Deaths'].tolist()
    
    list_delta_confirmed = []
    list_delta_death = []
    list_fatality_rate = []
    
    for j in range(len(list_confirmed)):
        list_fatality_rate.append(get_fatal_rate(list_confirmed[j], list_death[j]))
        if j == 0:
            list_delta_confirmed.append(list_confirmed[j])
            list_delta_death.append(list_death[j])
        else:
            list_delta_confirmed.append(get_zero_or_result(list_confirmed[j], list_confirmed[j - 1]))
            list_delta_death.append(get_zero_or_result(list_death[j], list_death[j - 1]))
            
    df_current_by_region['New Confirmed'] = list_delta_confirmed
    df_current_by_region['New Deaths'] = list_delta_death
    df_current_by_region['Fatality Ratio'] = list_fatality_rate
    
    dfs_by_regions[list_codes[i]] = df_current_by_region

processing: AFG
processing: AGO
processing: ALB
processing: AND
processing: ARE
processing: ARG
processing: ARM
processing: ATG
processing: AUS
processing: AUT
processing: AZE
processing: BDI
processing: BEL
processing: BEN
processing: BFA
processing: BGD
processing: BGR
processing: BHR
processing: BHS
processing: BIH
processing: BLR
processing: BLZ
processing: BOL
processing: BRA
processing: BRB
processing: BRN
processing: BTN
processing: BWA
processing: CAF
processing: CAN
processing: CHE
processing: CHL
processing: CHN
processing: CIV
processing: CMR
processing: COD
processing: COG
processing: COL
processing: COM
processing: CPV
processing: CRI
processing: CUB
processing: CYP
processing: CZE
processing: DEU
processing: DJI
processing: DMA
processing: DNK
processing: DOM
processing: DZA
processing: ECU
processing: EGY
processing: ERI
processing: ESP
processing: EST
processing: ETH
processing: FIN
processing: FJI
processing: FRA
processing: FSM
processing: GAB
processing: GBR
processing: GEO
processing: GHA
processing: GIN
processing: GMB
processing: GNB
processing: GNQ
processing: GRC
processing: GRD
processing: GTM
processing: GUY
processing: HND
processing: HRV
processing: HTI
processing: HUN
processing: IDN
processing: IND
processing: IRL
processing: IRN
processing: IRQ
processing: ISL
processing: ISR
processing: ITA
processing: JAM
processing: JOR
processing: JPN
processing: KAZ
processing: KEN
processing: KGZ
processing: KHM
processing: KIR
processing: KOR
processing: KWT
processing: LAO
processing: LBN
processing: LBR
processing: LBY
processing: LIE
processing: LKA
processing: LSO
processing: LTU
processing: LUX
processing: LVA
processing: MAR
processing: MCO
processing: MDA
processing: MDG
processing: MDV
processing: MEX
processing: MHL
processing: MKD
processing: MLI
processing: MLT
processing: MMR
processing: MNE
processing: MNG
processing: MOZ
processing: MRT
processing: MUS
processing: MWI
processing: MYS
processing: NAM
processing: NER
processing: NGA
processing: NIC
processing: NLD
processing: NOR
processing: NPL
processing: NZL
processing: OMN
processing: PAK
processing: PAN
processing: PER
processing: PHL
processing: PLW
processing: PNG
processing: POL
processing: PRT
processing: PRY
processing: PSE
processing: QAT
processing: ROU
processing: RUS
processing: RWA
processing: SAU
processing: SDN
processing: SEN
processing: SGP
processing: SLB
processing: SLE
processing: SLV
processing: SMR
processing: SOM
processing: SRB
processing: SSD
processing: SUR
processing: SVK
processing: SVN
processing: SWE
processing: SWZ
processing: SYC
processing: SYR
processing: TCD
processing: TGO
processing: THA
processing: TJK
processing: TLS
processing: TON
processing: TTO
processing: TUN
processing: TUR
processing: TZA
processing: UGA
processing: UKR
processing: URY
processing: USA
processing: UZB
processing: VEN
processing: VNM
processing: VUT
processing: WSM
processing: XKX
processing: YEM
processing: ZAF
processing: ZMB
processing: ZWE

In [6]:
dfs_by_regions['CHN']

,Country_Region,Confirmed,Deaths,date,Short Code,New Confirmed,New Deaths,Fatality Ratio
26197,Mainland China,547.0,17.0,2020-01-22,CHN,547.0,17.0,0.031079
26198,Mainland China,1082.0,34.0,2020-01-23,CHN,535.0,17.0,0.031423
26199,Mainland China,916.0,26.0,2020-01-24,CHN,0.0,0.0,0.028384
26200,Mainland China,1399.0,42.0,2020-01-25,CHN,483.0,16.0,0.030021
26201,Mainland China,2062.0,56.0,2020-01-26,CHN,663.0,14.0,0.027158
...,...,...,...,...,...,...,...,...
27052,China,2413319.0,14600.0,2022-05-26,CHN,3697.0,3.0,0.006050
27053,China,2413665.0,14601.0,2022-05-27,CHN,346.0,1.0,0.006049
27054,China,2420327.0,14602.0,2022-05-28,CHN,6662.0,1.0,0.006033
27055,China,2423500.0,14602.0,2022-05-29,CHN,3173.0,0.0,0.006025
27056,China,2426568.0,14604.0,2022-05-30,CHN,3068.0,2.0,0.006018

In [7]:
df_current = dfs_by_regions['GBR']

df_current[df_current['date'] == datetime.datetime.strptime('2022-05-25', '%Y-%m-%d')]

,Country_Region,Confirmed,Deaths,date,Short Code,New Confirmed,New Deaths,Fatality Ratio
50475,United Kingdom,22462129.0,178973.0,2022-05-25,GBR,6737.0,93.0,0.007968

In [8]:
df_current = dfs_by_regions['GBR']

df_current[df_current['date'] == datetime.datetime.strptime('2022-05-26', '%Y-%m-%d')]

,Country_Region,Confirmed,Deaths,date,Short Code,New Confirmed,New Deaths,Fatality Ratio
50476,United Kingdom,22458340.0,179064.0,2022-05-26,GBR,0.0,91.0,0.007973

### 5.2 Export

In [9]:
dfs_merged_regions = pd.concat(list(dfs_by_regions.values())).reset_index(drop=True)

In [10]:
dfs_merged_regions.columns = ['Country Region Name', 'Confirmed', 'Deaths', 'Date', 'Country Code', 'New Confirmed', 'New Deaths', 'Fatality Ratio']

In [11]:
dfs_merged_regions.head()

,Country Region Name,Confirmed,Deaths,Date,Country Code,New Confirmed,New Deaths,Fatality Ratio
0,Afghanistan,5.0,0.0,2020-02-24,AFG,5.0,0.0,0.0
1,Afghanistan,5.0,0.0,2020-02-25,AFG,0.0,0.0,0.0
2,Afghanistan,5.0,0.0,2020-02-26,AFG,0.0,0.0,0.0
3,Afghanistan,5.0,0.0,2020-02-27,AFG,0.0,0.0,0.0
4,Afghanistan,5.0,0.0,2020-02-28,AFG,0.0,0.0,0.0

In [12]:
dfs_merged_regions = dfs_merged_regions.sort_values(by=["Country Code", "Date"]).reset_index(drop=True)

dfs_merged_regions.to_csv(BASE_PATH_OUT + "covid_data_v3.csv", date_format='%m/%d/%Y', index=False)

In [13]:
# sanity check
dfs_merged_regions[dfs_merged_regions['Country Code'] == 'CHN']

,Country Region Name,Confirmed,Deaths,Date,Country Code,New Confirmed,New Deaths,Fatality Ratio
26197,Mainland China,547.0,17.0,2020-01-22,CHN,547.0,17.0,0.031079
26198,Mainland China,1082.0,34.0,2020-01-23,CHN,535.0,17.0,0.031423
26199,Mainland China,916.0,26.0,2020-01-24,CHN,0.0,0.0,0.028384
26200,Mainland China,1399.0,42.0,2020-01-25,CHN,483.0,16.0,0.030021
26201,Mainland China,2062.0,56.0,2020-01-26,CHN,663.0,14.0,0.027158
...,...,...,...,...,...,...,...,...
27052,China,2413319.0,14600.0,2022-05-26,CHN,3697.0,3.0,0.006050
27053,China,2413665.0,14601.0,2022-05-27,CHN,346.0,1.0,0.006049
27054,China,2420327.0,14602.0,2022-05-28,CHN,6662.0,1.0,0.006033
27055,China,2423500.0,14602.0,2022-05-29,CHN,3173.0,0.0,0.006025
27056,China,2426568.0,14604.0,2022-05-30,CHN,3068.0,2.0,0.006018